#!/bin/bash

if [[ -f ~/.bashrc ]]; then
  source ~/.bashrc
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Added by Toolbox App
export PATH="$PATH:/home/omar/.local/share/JetBrains/Toolbox/scripts"

# Rust package manager (cargo)
. "$HOME/.cargo/env"
