#!/bin/bash

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# ----------------------------------------------------------------------
# | Init                                                               |
# ----------------------------------------------------------------------

# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
ROOT_DIR="$(realpath "$DIR/../..")"
[ ! -v DOTFILES_ROOT_DIR ] && source "$ROOT_DIR/scripts/utils.sh"

TOPIC_NAME="shell"
TOPIC_DIR="$DOTFILES_SOURCE_DIR/$TOPIC_NAME"

# ----------------------------------------------------------------------
# | Main                                                               |
# ----------------------------------------------------------------------

main() {
  load_topics $TOPIC_DIR
}

main
