#!/bin/bash

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# source scripts
ROOT_DIR="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))/../.."
source "$ROOT_DIR/scripts/utils.sh"
source "$DOTFILES_SCRIPTS_DIR/load_topics.sh"

# init bash
TOPIC_NAME="shell"
TOPIC_DIR="$DOTFILES_SOURCE_DIR/$TOPIC_NAME"
load_topics $TOPIC_DIR

# Welcome Screen
figlet -c -t -f "ANSI Shadow" "Basbousa"
