#!/bin/bash

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# ----------------------------------------------------------------------
# | Init                                                               |
# ----------------------------------------------------------------------

# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

# ----------------------------------------------------------------------
# | Main                                                               |
# ----------------------------------------------------------------------

main() {

  local DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
  local ROOT_DIR="$(realpath "$DIR/../..")"

  [ ! -v DOTFILES_ROOT_DIR ] && source "$ROOT_DIR/scripts/utils.sh"

  local TOPIC_NAME="shell"
  local TOPIC_DIR="$DOTFILES_SOURCE_DIR/$TOPIC_NAME"

  load_topics $TOPIC_DIR

  cleanup
  unset -f cleanup

}

main
