name: Test Dotfiles

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  test-dotfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup test environment and run tests
        run: ./test/setup.sh

