name: Dotfiles

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  test-dotfiles--local:
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: test/docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image of test environment
        run: docker compose build local

      - name: Run tests inside the docker container
        run: docker compose up local

  test-dotfiles--remote:
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: test/docker-compose.yml
      RAW_CONTENT_URL:
        "https://raw.githubusercontent.com\
        /${{ github.repository }}\
        /main"
        #/${{ github.head_ref || github.ref_name }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image of test environment
        run: docker compose build remote

      - name: Run tests inside the docker container
        run: docker compose up remote

